"""add idempotency key to task

Revision ID: a253858d282f
Revises: 84ee6f6f6344
Create Date: 2026-04-17 15:45:27.861259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a253858d282f'
down_revision: Union[str, Sequence[str], None] = '84ee6f6f6344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_column('tasks', 'idempotency_key')
    # ### end Alembic commands ###
